---
# This task will override the default "empty" pullsecret from the registry playbook
# with the content of the pullsecret defined in the OKD playbook
- name: set pullsecret with new auth
  set_fact:
    kubeinit_registry_pullsecret: '{{ kubeinit_okd_registry_pullsecret }}'
