---

- name: render the sync template
  template:
    src: "sync.yml.j2"
    dest: 'sync.yml'
    mode: '0755'

- name: Mirror OKD remote registry to local
  shell: |
    set -o pipefail
    set -e

    oc adm \
        release mirror \
        --registry-config={{ kubeinit_registry_auth_file }} \
        --from={{ kubeinit_okd_registry }}/{{ kubeinit_okd_registry_organization }}/{{ kubeinit_okd_registry_repository }}:{{ kubeinit_okd_registry_release_tag }} \
        --to={{ kubeinit_registry_uri }}/{{ kubeinit_okd_registry_repository }} \
        --to-release-image={{ kubeinit_registry_uri }}/{{ kubeinit_okd_registry_repository }}:{{ kubeinit_okd_registry_release_tag }} \
        2>&1 | tee mirror-output.txt

    oc adm \
        release extract \
        --registry-config={{ kubeinit_registry_auth_file }} \
        --command=openshift-install "{{ kubeinit_registry_uri }}/{{ kubeinit_okd_registry_repository }}:{{ kubeinit_okd_registry_release_tag }}"

    # This will override the current installer binary
    cp openshift-install /usr/local/bin/
  args:
    executable: /bin/bash
  register: mirror_registry
  changed_when: "mirror_registry.rc == 0"
